### ISSUE TITLE
Nanoseconds was not in the range

### ISSUE THREAD

**Issue by manuerumx** [Chekote/BehatRetryExtension#10]
#### Description
Using the extension with the optional configuration suggested:

```yaml
# behat.yml
default:
    # ...
    extensions:
        Chekote\BehatRetryExtension:
          timeout: 10
          interval: 1000000000
          strictKeywords: true
```
Returns and error when some scenarios fail and tries to use the retry functionality

#### Error
The warning/error returned is the next:

> Warning: time_nanosleep(): nanoseconds was not in the range 0 to 999 999 999 or seconds was negative
